/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MvsAbout {
    'aboutTitle': any;
    'text': any;
  }
  interface MvsAnchor {
    'href': string;
  }
  interface MvsBarraGoverno {}
  interface MvsBase {}
  interface MvsBg {}
  interface MvsBigNumber {
    'elements': any;
  }
  interface MvsButton {
    /**
    * Caso `true`, desabilita o botão.
    */
    'disabled': boolean;
    /**
    * Caso `true`, botão terá largura 100%.
    */
    'full': boolean;
    /**
    * Caso `true`, botão terá tema light/night mode.
    */
    'light': boolean;
    /**
    * Define o tipo do botão.
    */
    'type': 'button' | 'submit' | 'reset';
    /**
    * Define estilo do botão.
    */
    'variant': 'flat' | 'ghost' | 'contained';
  }
  interface MvsCard {
    'alt': string;
    'button': string;
    'cardtitle': string;
    'link': string;
    'media': string;
    'overline': any;
    'subtitle': string;
    'text': string;
    'width': number;
  }
  interface MvsCardExpander {
    'alt': string;
    'cardtitle': string;
    'link': string;
    'media': string;
    'overline': any;
    'subtitle': string;
    'text': string;
  }
  interface MvsCardList {
    'data': { overline: string; title: string; subtitle: string; text: string; button: string; link: string; media: string; }[];
  }
  interface MvsContactList {}
  interface MvsCountdown {
    'deadline': string;
    'endMessage': string;
    'hours': number;
    'minutes': number;
    'seconds': number;
    'spanProcent': any;
  }
  interface MvsDivider {}
  interface MvsFigure {
    'alt': string;
    'src': string;
  }
  interface MvsFigureCaption {
    'alt': string;
    'bold': boolean;
    'boldspotlight': boolean;
    'boldtext': boolean;
    'italic': boolean;
    'italicspotlight': boolean;
    'italictext': boolean;
    'src': string;
  }
  interface MvsFlex {
    /**
    * Altera visualização de flex para block.
    */
    'block': boolean;
    /**
    * Caso `true`, o componente se comportará como `container` capaz de receber `items`.
    */
    'container': boolean;
    /**
    * Caso `true`, o componente se comportará como `item`, contido em um `container`.
    */
    'item': boolean;
    /**
    * Largura do componente no breakpoint Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'lg': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Medium, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'md': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Small, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'sm': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Define espaçamento entre componentes do tipo `item`. Usando somente em componentes tipo `container`.
    */
    'spacing': string;
    /**
    * Largura do componente no breakpoint Extra Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'xl': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  }
  interface MvsFlexgrid {
    /**
    * Altera visualização de flex para block.
    */
    'block': boolean;
    /**
    * Caso `true`, o componente se comportará como `container` capaz de receber `items`.
    */
    'container': boolean;
    /**
    * Caso `true`, o componente se comportará como `item`, contido em um `container`.
    */
    'item': boolean;
    /**
    * Largura do componente no breakpoint Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'lg': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Medium, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'md': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Small, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'sm': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Define espaçamento entre componentes do tipo `item`. Usando somente em componentes tipo `container`.
    */
    'spacing': string;
    /**
    * Largura do componente no breakpoint Extra Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'xl': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  }
  interface MvsFooter {
    'icons': { rodape_logo: string; }[];
  }
  interface MvsForm {}
  interface MvsGrid {
    'marginzero': boolean;
  }
  interface MvsHero {
    'background': string;
    'bgimg': string;
    'button': string;
    'herotitle': string;
  }
  interface MvsIconbutton {
    'disabled': boolean;
    'type': string;
  }
  interface MvsMark {}
  interface MvsMobButton {
    'open': boolean;
  }
  interface MvsMobDrawer {
    'open': boolean;
  }
  interface MvsNavbar {
    'color': 'inherit' | 'primary' | 'secondary' | 'default';
    'lastScrollY': number;
    'links': { name: string; url: string }[];
    'logo': string;
    'open': boolean;
    'position': 'fixed' | 'sticky' | 'absolute' | 'static' | 'relative';
    'setClass': string;
  }
  interface MvsNavbutton {
    'color': 'primary' | 'white' | 'black';
    'disabled': boolean;
    'type': string;
  }
  interface MvsOverline {}
  interface MvsParagraph {
    /**
    * Altera o parágrafo para tamanho reduzido (body 2).
    */
    'bodytwo': boolean;
    /**
    * Ativa ou desativa estilização de capitular.
    */
    'capitular': boolean;
    /**
    * Altera a cor do texto.
    */
    'color': 'primary' | 'secondary' | 'white';
  }
  interface MvsPre {}
  interface MvsQuestionsCommon {}
  interface MvsShape {
    'bg': | 'primary'
    | 'secondary'
    | 'black'
    | 'dark'
    | 'medium'
    | 'light'
    | 'white'
    | 'error'
    | 'warning'
    | 'confirm';
  }
  interface MvsSinglePage {
    'data': any;
    'numbers': any;
  }
  interface MvsStrong {}
  interface MvsSubtitle {
    'type': 'one' | 'two';
  }
  interface MvsTitle {
    /**
    * Define estilo de título a ser usado pelo componente.
    */
    'level': true | false | 't1' | 't2' | 't3' | 't4' | 't5' | 't6';
    /**
    * Sobreescreve o tag html definido automaticamente.
    */
    'override': true | false | 1 | 2 | 3 | 4 | 5 | 6;
    /**
    * Propriedade interna que define automaticamente a tag H a ser usada.
    */
    'rank': number;
    /**
    * Define texto de cor branca, para fundos escuros.
    */
    'white': boolean;
  }
  interface MvsTooltip {
    /**
    * Define conteúdo do tooltip.
    */
    'label': string;
    /**
    * Define largura do tooltip.
    */
    'length': string;
  }
}

declare global {


  interface HTMLMvsAboutElement extends Components.MvsAbout, HTMLStencilElement {}
  var HTMLMvsAboutElement: {
    prototype: HTMLMvsAboutElement;
    new (): HTMLMvsAboutElement;
  };

  interface HTMLMvsAnchorElement extends Components.MvsAnchor, HTMLStencilElement {}
  var HTMLMvsAnchorElement: {
    prototype: HTMLMvsAnchorElement;
    new (): HTMLMvsAnchorElement;
  };

  interface HTMLMvsBarraGovernoElement extends Components.MvsBarraGoverno, HTMLStencilElement {}
  var HTMLMvsBarraGovernoElement: {
    prototype: HTMLMvsBarraGovernoElement;
    new (): HTMLMvsBarraGovernoElement;
  };

  interface HTMLMvsBaseElement extends Components.MvsBase, HTMLStencilElement {}
  var HTMLMvsBaseElement: {
    prototype: HTMLMvsBaseElement;
    new (): HTMLMvsBaseElement;
  };

  interface HTMLMvsBgElement extends Components.MvsBg, HTMLStencilElement {}
  var HTMLMvsBgElement: {
    prototype: HTMLMvsBgElement;
    new (): HTMLMvsBgElement;
  };

  interface HTMLMvsBigNumberElement extends Components.MvsBigNumber, HTMLStencilElement {}
  var HTMLMvsBigNumberElement: {
    prototype: HTMLMvsBigNumberElement;
    new (): HTMLMvsBigNumberElement;
  };

  interface HTMLMvsButtonElement extends Components.MvsButton, HTMLStencilElement {}
  var HTMLMvsButtonElement: {
    prototype: HTMLMvsButtonElement;
    new (): HTMLMvsButtonElement;
  };

  interface HTMLMvsCardElement extends Components.MvsCard, HTMLStencilElement {}
  var HTMLMvsCardElement: {
    prototype: HTMLMvsCardElement;
    new (): HTMLMvsCardElement;
  };

  interface HTMLMvsCardExpanderElement extends Components.MvsCardExpander, HTMLStencilElement {}
  var HTMLMvsCardExpanderElement: {
    prototype: HTMLMvsCardExpanderElement;
    new (): HTMLMvsCardExpanderElement;
  };

  interface HTMLMvsCardListElement extends Components.MvsCardList, HTMLStencilElement {}
  var HTMLMvsCardListElement: {
    prototype: HTMLMvsCardListElement;
    new (): HTMLMvsCardListElement;
  };

  interface HTMLMvsContactListElement extends Components.MvsContactList, HTMLStencilElement {}
  var HTMLMvsContactListElement: {
    prototype: HTMLMvsContactListElement;
    new (): HTMLMvsContactListElement;
  };

  interface HTMLMvsCountdownElement extends Components.MvsCountdown, HTMLStencilElement {}
  var HTMLMvsCountdownElement: {
    prototype: HTMLMvsCountdownElement;
    new (): HTMLMvsCountdownElement;
  };

  interface HTMLMvsDividerElement extends Components.MvsDivider, HTMLStencilElement {}
  var HTMLMvsDividerElement: {
    prototype: HTMLMvsDividerElement;
    new (): HTMLMvsDividerElement;
  };

  interface HTMLMvsFigureElement extends Components.MvsFigure, HTMLStencilElement {}
  var HTMLMvsFigureElement: {
    prototype: HTMLMvsFigureElement;
    new (): HTMLMvsFigureElement;
  };

  interface HTMLMvsFigureCaptionElement extends Components.MvsFigureCaption, HTMLStencilElement {}
  var HTMLMvsFigureCaptionElement: {
    prototype: HTMLMvsFigureCaptionElement;
    new (): HTMLMvsFigureCaptionElement;
  };

  interface HTMLMvsFlexElement extends Components.MvsFlex, HTMLStencilElement {}
  var HTMLMvsFlexElement: {
    prototype: HTMLMvsFlexElement;
    new (): HTMLMvsFlexElement;
  };

  interface HTMLMvsFlexgridElement extends Components.MvsFlexgrid, HTMLStencilElement {}
  var HTMLMvsFlexgridElement: {
    prototype: HTMLMvsFlexgridElement;
    new (): HTMLMvsFlexgridElement;
  };

  interface HTMLMvsFooterElement extends Components.MvsFooter, HTMLStencilElement {}
  var HTMLMvsFooterElement: {
    prototype: HTMLMvsFooterElement;
    new (): HTMLMvsFooterElement;
  };

  interface HTMLMvsFormElement extends Components.MvsForm, HTMLStencilElement {}
  var HTMLMvsFormElement: {
    prototype: HTMLMvsFormElement;
    new (): HTMLMvsFormElement;
  };

  interface HTMLMvsGridElement extends Components.MvsGrid, HTMLStencilElement {}
  var HTMLMvsGridElement: {
    prototype: HTMLMvsGridElement;
    new (): HTMLMvsGridElement;
  };

  interface HTMLMvsHeroElement extends Components.MvsHero, HTMLStencilElement {}
  var HTMLMvsHeroElement: {
    prototype: HTMLMvsHeroElement;
    new (): HTMLMvsHeroElement;
  };

  interface HTMLMvsIconbuttonElement extends Components.MvsIconbutton, HTMLStencilElement {}
  var HTMLMvsIconbuttonElement: {
    prototype: HTMLMvsIconbuttonElement;
    new (): HTMLMvsIconbuttonElement;
  };

  interface HTMLMvsMarkElement extends Components.MvsMark, HTMLStencilElement {}
  var HTMLMvsMarkElement: {
    prototype: HTMLMvsMarkElement;
    new (): HTMLMvsMarkElement;
  };

  interface HTMLMvsMobButtonElement extends Components.MvsMobButton, HTMLStencilElement {}
  var HTMLMvsMobButtonElement: {
    prototype: HTMLMvsMobButtonElement;
    new (): HTMLMvsMobButtonElement;
  };

  interface HTMLMvsMobDrawerElement extends Components.MvsMobDrawer, HTMLStencilElement {}
  var HTMLMvsMobDrawerElement: {
    prototype: HTMLMvsMobDrawerElement;
    new (): HTMLMvsMobDrawerElement;
  };

  interface HTMLMvsNavbarElement extends Components.MvsNavbar, HTMLStencilElement {}
  var HTMLMvsNavbarElement: {
    prototype: HTMLMvsNavbarElement;
    new (): HTMLMvsNavbarElement;
  };

  interface HTMLMvsNavbuttonElement extends Components.MvsNavbutton, HTMLStencilElement {}
  var HTMLMvsNavbuttonElement: {
    prototype: HTMLMvsNavbuttonElement;
    new (): HTMLMvsNavbuttonElement;
  };

  interface HTMLMvsOverlineElement extends Components.MvsOverline, HTMLStencilElement {}
  var HTMLMvsOverlineElement: {
    prototype: HTMLMvsOverlineElement;
    new (): HTMLMvsOverlineElement;
  };

  interface HTMLMvsParagraphElement extends Components.MvsParagraph, HTMLStencilElement {}
  var HTMLMvsParagraphElement: {
    prototype: HTMLMvsParagraphElement;
    new (): HTMLMvsParagraphElement;
  };

  interface HTMLMvsPreElement extends Components.MvsPre, HTMLStencilElement {}
  var HTMLMvsPreElement: {
    prototype: HTMLMvsPreElement;
    new (): HTMLMvsPreElement;
  };

  interface HTMLMvsQuestionsCommonElement extends Components.MvsQuestionsCommon, HTMLStencilElement {}
  var HTMLMvsQuestionsCommonElement: {
    prototype: HTMLMvsQuestionsCommonElement;
    new (): HTMLMvsQuestionsCommonElement;
  };

  interface HTMLMvsShapeElement extends Components.MvsShape, HTMLStencilElement {}
  var HTMLMvsShapeElement: {
    prototype: HTMLMvsShapeElement;
    new (): HTMLMvsShapeElement;
  };

  interface HTMLMvsSinglePageElement extends Components.MvsSinglePage, HTMLStencilElement {}
  var HTMLMvsSinglePageElement: {
    prototype: HTMLMvsSinglePageElement;
    new (): HTMLMvsSinglePageElement;
  };

  interface HTMLMvsStrongElement extends Components.MvsStrong, HTMLStencilElement {}
  var HTMLMvsStrongElement: {
    prototype: HTMLMvsStrongElement;
    new (): HTMLMvsStrongElement;
  };

  interface HTMLMvsSubtitleElement extends Components.MvsSubtitle, HTMLStencilElement {}
  var HTMLMvsSubtitleElement: {
    prototype: HTMLMvsSubtitleElement;
    new (): HTMLMvsSubtitleElement;
  };

  interface HTMLMvsTitleElement extends Components.MvsTitle, HTMLStencilElement {}
  var HTMLMvsTitleElement: {
    prototype: HTMLMvsTitleElement;
    new (): HTMLMvsTitleElement;
  };

  interface HTMLMvsTooltipElement extends Components.MvsTooltip, HTMLStencilElement {}
  var HTMLMvsTooltipElement: {
    prototype: HTMLMvsTooltipElement;
    new (): HTMLMvsTooltipElement;
  };
  interface HTMLElementTagNameMap {
    'mvs-about': HTMLMvsAboutElement;
    'mvs-anchor': HTMLMvsAnchorElement;
    'mvs-barra-governo': HTMLMvsBarraGovernoElement;
    'mvs-base': HTMLMvsBaseElement;
    'mvs-bg': HTMLMvsBgElement;
    'mvs-big-number': HTMLMvsBigNumberElement;
    'mvs-button': HTMLMvsButtonElement;
    'mvs-card': HTMLMvsCardElement;
    'mvs-card-expander': HTMLMvsCardExpanderElement;
    'mvs-card-list': HTMLMvsCardListElement;
    'mvs-contact-list': HTMLMvsContactListElement;
    'mvs-countdown': HTMLMvsCountdownElement;
    'mvs-divider': HTMLMvsDividerElement;
    'mvs-figure': HTMLMvsFigureElement;
    'mvs-figure-caption': HTMLMvsFigureCaptionElement;
    'mvs-flex': HTMLMvsFlexElement;
    'mvs-flexgrid': HTMLMvsFlexgridElement;
    'mvs-footer': HTMLMvsFooterElement;
    'mvs-form': HTMLMvsFormElement;
    'mvs-grid': HTMLMvsGridElement;
    'mvs-hero': HTMLMvsHeroElement;
    'mvs-iconbutton': HTMLMvsIconbuttonElement;
    'mvs-mark': HTMLMvsMarkElement;
    'mvs-mob-button': HTMLMvsMobButtonElement;
    'mvs-mob-drawer': HTMLMvsMobDrawerElement;
    'mvs-navbar': HTMLMvsNavbarElement;
    'mvs-navbutton': HTMLMvsNavbuttonElement;
    'mvs-overline': HTMLMvsOverlineElement;
    'mvs-paragraph': HTMLMvsParagraphElement;
    'mvs-pre': HTMLMvsPreElement;
    'mvs-questions-common': HTMLMvsQuestionsCommonElement;
    'mvs-shape': HTMLMvsShapeElement;
    'mvs-single-page': HTMLMvsSinglePageElement;
    'mvs-strong': HTMLMvsStrongElement;
    'mvs-subtitle': HTMLMvsSubtitleElement;
    'mvs-title': HTMLMvsTitleElement;
    'mvs-tooltip': HTMLMvsTooltipElement;
  }
}

declare namespace LocalJSX {
  interface MvsAbout extends JSXBase.HTMLAttributes<HTMLMvsAboutElement> {
    'aboutTitle'?: any;
    'text'?: any;
  }
  interface MvsAnchor extends JSXBase.HTMLAttributes<HTMLMvsAnchorElement> {
    'href'?: string;
  }
  interface MvsBarraGoverno extends JSXBase.HTMLAttributes<HTMLMvsBarraGovernoElement> {}
  interface MvsBase extends JSXBase.HTMLAttributes<HTMLMvsBaseElement> {}
  interface MvsBg extends JSXBase.HTMLAttributes<HTMLMvsBgElement> {}
  interface MvsBigNumber extends JSXBase.HTMLAttributes<HTMLMvsBigNumberElement> {
    'elements'?: any;
  }
  interface MvsButton extends JSXBase.HTMLAttributes<HTMLMvsButtonElement> {
    /**
    * Caso `true`, desabilita o botão.
    */
    'disabled'?: boolean;
    /**
    * Caso `true`, botão terá largura 100%.
    */
    'full'?: boolean;
    /**
    * Caso `true`, botão terá tema light/night mode.
    */
    'light'?: boolean;
    /**
    * Define o tipo do botão.
    */
    'type'?: 'button' | 'submit' | 'reset';
    /**
    * Define estilo do botão.
    */
    'variant'?: 'flat' | 'ghost' | 'contained';
  }
  interface MvsCard extends JSXBase.HTMLAttributes<HTMLMvsCardElement> {
    'alt'?: string;
    'button'?: string;
    'cardtitle'?: string;
    'link'?: string;
    'media'?: string;
    'overline'?: any;
    'subtitle'?: string;
    'text'?: string;
    'width'?: number;
  }
  interface MvsCardExpander extends JSXBase.HTMLAttributes<HTMLMvsCardExpanderElement> {
    'alt'?: string;
    'cardtitle'?: string;
    'link'?: string;
    'media'?: string;
    'overline'?: any;
    'subtitle'?: string;
    'text'?: string;
  }
  interface MvsCardList extends JSXBase.HTMLAttributes<HTMLMvsCardListElement> {
    'data'?: { overline: string; title: string; subtitle: string; text: string; button: string; link: string; media: string; }[];
  }
  interface MvsContactList extends JSXBase.HTMLAttributes<HTMLMvsContactListElement> {}
  interface MvsCountdown extends JSXBase.HTMLAttributes<HTMLMvsCountdownElement> {
    'deadline'?: string;
    'endMessage'?: string;
    'hours'?: number;
    'minutes'?: number;
    'seconds'?: number;
    'spanProcent'?: any;
  }
  interface MvsDivider extends JSXBase.HTMLAttributes<HTMLMvsDividerElement> {}
  interface MvsFigure extends JSXBase.HTMLAttributes<HTMLMvsFigureElement> {
    'alt'?: string;
    'src'?: string;
  }
  interface MvsFigureCaption extends JSXBase.HTMLAttributes<HTMLMvsFigureCaptionElement> {
    'alt'?: string;
    'bold'?: boolean;
    'boldspotlight'?: boolean;
    'boldtext'?: boolean;
    'italic'?: boolean;
    'italicspotlight'?: boolean;
    'italictext'?: boolean;
    'src'?: string;
  }
  interface MvsFlex extends JSXBase.HTMLAttributes<HTMLMvsFlexElement> {
    /**
    * Altera visualização de flex para block.
    */
    'block'?: boolean;
    /**
    * Caso `true`, o componente se comportará como `container` capaz de receber `items`.
    */
    'container'?: boolean;
    /**
    * Caso `true`, o componente se comportará como `item`, contido em um `container`.
    */
    'item'?: boolean;
    /**
    * Largura do componente no breakpoint Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'lg'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Medium, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'md'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Small, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'sm'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Define espaçamento entre componentes do tipo `item`. Usando somente em componentes tipo `container`.
    */
    'spacing'?: string;
    /**
    * Largura do componente no breakpoint Extra Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'xl'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  }
  interface MvsFlexgrid extends JSXBase.HTMLAttributes<HTMLMvsFlexgridElement> {
    /**
    * Altera visualização de flex para block.
    */
    'block'?: boolean;
    /**
    * Caso `true`, o componente se comportará como `container` capaz de receber `items`.
    */
    'container'?: boolean;
    /**
    * Caso `true`, o componente se comportará como `item`, contido em um `container`.
    */
    'item'?: boolean;
    /**
    * Largura do componente no breakpoint Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'lg'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Medium, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'md'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Small, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'sm'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Define espaçamento entre componentes do tipo `item`. Usando somente em componentes tipo `container`.
    */
    'spacing'?: string;
    /**
    * Largura do componente no breakpoint Extra Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'xl'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  }
  interface MvsFooter extends JSXBase.HTMLAttributes<HTMLMvsFooterElement> {
    'icons'?: { rodape_logo: string; }[];
  }
  interface MvsForm extends JSXBase.HTMLAttributes<HTMLMvsFormElement> {}
  interface MvsGrid extends JSXBase.HTMLAttributes<HTMLMvsGridElement> {
    'marginzero'?: boolean;
  }
  interface MvsHero extends JSXBase.HTMLAttributes<HTMLMvsHeroElement> {
    'background'?: string;
    'bgimg'?: string;
    'button'?: string;
    'herotitle'?: string;
  }
  interface MvsIconbutton extends JSXBase.HTMLAttributes<HTMLMvsIconbuttonElement> {
    'disabled'?: boolean;
    'type'?: string;
  }
  interface MvsMark extends JSXBase.HTMLAttributes<HTMLMvsMarkElement> {}
  interface MvsMobButton extends JSXBase.HTMLAttributes<HTMLMvsMobButtonElement> {
    'open'?: boolean;
  }
  interface MvsMobDrawer extends JSXBase.HTMLAttributes<HTMLMvsMobDrawerElement> {
    'open'?: boolean;
  }
  interface MvsNavbar extends JSXBase.HTMLAttributes<HTMLMvsNavbarElement> {
    'color'?: 'inherit' | 'primary' | 'secondary' | 'default';
    'lastScrollY'?: number;
    'links'?: { name: string; url: string }[];
    'logo'?: string;
    'open'?: boolean;
    'position'?: 'fixed' | 'sticky' | 'absolute' | 'static' | 'relative';
    'setClass'?: string;
  }
  interface MvsNavbutton extends JSXBase.HTMLAttributes<HTMLMvsNavbuttonElement> {
    'color'?: 'primary' | 'white' | 'black';
    'disabled'?: boolean;
    'type'?: string;
  }
  interface MvsOverline extends JSXBase.HTMLAttributes<HTMLMvsOverlineElement> {}
  interface MvsParagraph extends JSXBase.HTMLAttributes<HTMLMvsParagraphElement> {
    /**
    * Altera o parágrafo para tamanho reduzido (body 2).
    */
    'bodytwo'?: boolean;
    /**
    * Ativa ou desativa estilização de capitular.
    */
    'capitular'?: boolean;
    /**
    * Altera a cor do texto.
    */
    'color'?: 'primary' | 'secondary' | 'white';
  }
  interface MvsPre extends JSXBase.HTMLAttributes<HTMLMvsPreElement> {}
  interface MvsQuestionsCommon extends JSXBase.HTMLAttributes<HTMLMvsQuestionsCommonElement> {}
  interface MvsShape extends JSXBase.HTMLAttributes<HTMLMvsShapeElement> {
    'bg'?: | 'primary'
    | 'secondary'
    | 'black'
    | 'dark'
    | 'medium'
    | 'light'
    | 'white'
    | 'error'
    | 'warning'
    | 'confirm';
  }
  interface MvsSinglePage extends JSXBase.HTMLAttributes<HTMLMvsSinglePageElement> {
    'data'?: any;
    'numbers'?: any;
  }
  interface MvsStrong extends JSXBase.HTMLAttributes<HTMLMvsStrongElement> {}
  interface MvsSubtitle extends JSXBase.HTMLAttributes<HTMLMvsSubtitleElement> {
    'type'?: 'one' | 'two';
  }
  interface MvsTitle extends JSXBase.HTMLAttributes<HTMLMvsTitleElement> {
    /**
    * Define estilo de título a ser usado pelo componente.
    */
    'level'?: true | false | 't1' | 't2' | 't3' | 't4' | 't5' | 't6';
    /**
    * Sobreescreve o tag html definido automaticamente.
    */
    'override'?: true | false | 1 | 2 | 3 | 4 | 5 | 6;
    /**
    * Propriedade interna que define automaticamente a tag H a ser usada.
    */
    'rank'?: number;
    /**
    * Define texto de cor branca, para fundos escuros.
    */
    'white'?: boolean;
  }
  interface MvsTooltip extends JSXBase.HTMLAttributes<HTMLMvsTooltipElement> {
    /**
    * Define conteúdo do tooltip.
    */
    'label'?: string;
    /**
    * Define largura do tooltip.
    */
    'length'?: string;
  }

  interface IntrinsicElements {
    'mvs-about': MvsAbout;
    'mvs-anchor': MvsAnchor;
    'mvs-barra-governo': MvsBarraGoverno;
    'mvs-base': MvsBase;
    'mvs-bg': MvsBg;
    'mvs-big-number': MvsBigNumber;
    'mvs-button': MvsButton;
    'mvs-card': MvsCard;
    'mvs-card-expander': MvsCardExpander;
    'mvs-card-list': MvsCardList;
    'mvs-contact-list': MvsContactList;
    'mvs-countdown': MvsCountdown;
    'mvs-divider': MvsDivider;
    'mvs-figure': MvsFigure;
    'mvs-figure-caption': MvsFigureCaption;
    'mvs-flex': MvsFlex;
    'mvs-flexgrid': MvsFlexgrid;
    'mvs-footer': MvsFooter;
    'mvs-form': MvsForm;
    'mvs-grid': MvsGrid;
    'mvs-hero': MvsHero;
    'mvs-iconbutton': MvsIconbutton;
    'mvs-mark': MvsMark;
    'mvs-mob-button': MvsMobButton;
    'mvs-mob-drawer': MvsMobDrawer;
    'mvs-navbar': MvsNavbar;
    'mvs-navbutton': MvsNavbutton;
    'mvs-overline': MvsOverline;
    'mvs-paragraph': MvsParagraph;
    'mvs-pre': MvsPre;
    'mvs-questions-common': MvsQuestionsCommon;
    'mvs-shape': MvsShape;
    'mvs-single-page': MvsSinglePage;
    'mvs-strong': MvsStrong;
    'mvs-subtitle': MvsSubtitle;
    'mvs-title': MvsTitle;
    'mvs-tooltip': MvsTooltip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


