/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MvsAnchor {
    'href': string;
  }
  interface MvsAppBar {
    'color': 'inherit' | 'primary' | 'secondary' | 'default';
    'position': 'fixed' | 'sticky' | 'absolute' | 'static' | 'relative';
  }
  interface MvsBase {}
  interface MvsBg {}
  interface MvsButton {
    /**
    * Caso `true`, desabilita o botão.
    */
    'disabled': boolean;
    /**
    * Caso `true`, botão terá largura 100%.
    */
    'full': boolean;
    /**
    * Caso `true`, botão não terá margens.
    */
    'marginzero': boolean;
    /**
    * Define o tipo do botão.
    */
    'type': 'button' | 'submit' | 'reset';
    /**
    * Define estilo do botão.
    */
    'variant': 'text' | 'outlined' | 'contained';
  }
  interface MvsCard {
    'button': string;
    'cardtitle': any;
    'link': string;
    'overline': any;
    'subtitle': any;
    'width': number;
  }
  interface MvsDivider {}
  interface MvsFigure {
    'alt': string;
    'src': string;
  }
  interface MvsFigureCaption {
    'alt': string;
    'bold': boolean;
    'boldspotlight': boolean;
    'boldtext': boolean;
    'italic': boolean;
    'italicspotlight': boolean;
    'italictext': boolean;
    'src': string;
  }
  interface MvsFlexgrid {
    /**
    * Altera visualização de flex para block.
    */
    'block': boolean;
    /**
    * Caso `true`, o componente se comportará como `container` capaz de receber `items`.
    */
    'container': boolean;
    /**
    * Caso `true`, o componente se comportará como `item`, contido em um `container`.
    */
    'item': boolean;
    /**
    * Largura do componente no breakpoint Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'lg': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Medium, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'md': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Small, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'sm': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Define espaçamento entre componentes do tipo `item`. Usando somente em componentes tipo `container`.
    */
    'spacing': string;
    /**
    * Largura do componente no breakpoint Extra Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'xl': true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  }
  interface MvsIconbutton {
    'disabled': boolean;
    'type': string;
  }
  interface MvsMark {}
  interface MvsMobButton {
    'open': boolean;
  }
  interface MvsMobDrawer {
    'open': boolean;
  }
  interface MvsMobMenu {
    'open': boolean;
    'setClass': string;
  }
  interface MvsNavbar {
    'setClass': string;
  }
  interface MvsNavbutton {
    'contained': boolean;
    'disabled': boolean;
    'marginzero': boolean;
    'outlined': boolean;
    'type': string;
  }
  interface MvsOverline {}
  interface MvsParagraph {
    /**
    * Altera o parágrafo para tamanho reduzido (body 2).
    */
    'bodytwo': boolean;
    /**
    * Ativa ou desativa estilização de capitular.
    */
    'capitular': boolean;
  }
  interface MvsPre {}
  interface MvsStrong {}
  interface MvsSubtitle {
    'type': string;
  }
  interface MvsTitle {
    /**
    * Define estilo de título a ser usado pelo componente.
    */
    'level': true | false | 't1' | 't2' | 't3' | 't4' | 't5' | 't6';
    /**
    * Sobreescreve o tag html definido automaticamente.
    */
    'override': true | false | 1 | 2 | 3 | 4 | 5 | 6;
    /**
    * Propriedade interna que define automaticamente a tag H a ser usada.
    */
    'rank': number;
    /**
    * Define texto de cor branca, para fundos escuros.
    */
    'white': boolean;
  }
  interface MvsTooltip {
    /**
    * Define conteúdo do tooltip.
    */
    'label': string;
    /**
    * Define largura do tooltip.
    */
    'length': string;
  }
}

declare global {


  interface HTMLMvsAnchorElement extends Components.MvsAnchor, HTMLStencilElement {}
  var HTMLMvsAnchorElement: {
    prototype: HTMLMvsAnchorElement;
    new (): HTMLMvsAnchorElement;
  };

  interface HTMLMvsAppBarElement extends Components.MvsAppBar, HTMLStencilElement {}
  var HTMLMvsAppBarElement: {
    prototype: HTMLMvsAppBarElement;
    new (): HTMLMvsAppBarElement;
  };

  interface HTMLMvsBaseElement extends Components.MvsBase, HTMLStencilElement {}
  var HTMLMvsBaseElement: {
    prototype: HTMLMvsBaseElement;
    new (): HTMLMvsBaseElement;
  };

  interface HTMLMvsBgElement extends Components.MvsBg, HTMLStencilElement {}
  var HTMLMvsBgElement: {
    prototype: HTMLMvsBgElement;
    new (): HTMLMvsBgElement;
  };

  interface HTMLMvsButtonElement extends Components.MvsButton, HTMLStencilElement {}
  var HTMLMvsButtonElement: {
    prototype: HTMLMvsButtonElement;
    new (): HTMLMvsButtonElement;
  };

  interface HTMLMvsCardElement extends Components.MvsCard, HTMLStencilElement {}
  var HTMLMvsCardElement: {
    prototype: HTMLMvsCardElement;
    new (): HTMLMvsCardElement;
  };

  interface HTMLMvsDividerElement extends Components.MvsDivider, HTMLStencilElement {}
  var HTMLMvsDividerElement: {
    prototype: HTMLMvsDividerElement;
    new (): HTMLMvsDividerElement;
  };

  interface HTMLMvsFigureElement extends Components.MvsFigure, HTMLStencilElement {}
  var HTMLMvsFigureElement: {
    prototype: HTMLMvsFigureElement;
    new (): HTMLMvsFigureElement;
  };

  interface HTMLMvsFigureCaptionElement extends Components.MvsFigureCaption, HTMLStencilElement {}
  var HTMLMvsFigureCaptionElement: {
    prototype: HTMLMvsFigureCaptionElement;
    new (): HTMLMvsFigureCaptionElement;
  };

  interface HTMLMvsFlexgridElement extends Components.MvsFlexgrid, HTMLStencilElement {}
  var HTMLMvsFlexgridElement: {
    prototype: HTMLMvsFlexgridElement;
    new (): HTMLMvsFlexgridElement;
  };

  interface HTMLMvsIconbuttonElement extends Components.MvsIconbutton, HTMLStencilElement {}
  var HTMLMvsIconbuttonElement: {
    prototype: HTMLMvsIconbuttonElement;
    new (): HTMLMvsIconbuttonElement;
  };

  interface HTMLMvsMarkElement extends Components.MvsMark, HTMLStencilElement {}
  var HTMLMvsMarkElement: {
    prototype: HTMLMvsMarkElement;
    new (): HTMLMvsMarkElement;
  };

  interface HTMLMvsMobButtonElement extends Components.MvsMobButton, HTMLStencilElement {}
  var HTMLMvsMobButtonElement: {
    prototype: HTMLMvsMobButtonElement;
    new (): HTMLMvsMobButtonElement;
  };

  interface HTMLMvsMobDrawerElement extends Components.MvsMobDrawer, HTMLStencilElement {}
  var HTMLMvsMobDrawerElement: {
    prototype: HTMLMvsMobDrawerElement;
    new (): HTMLMvsMobDrawerElement;
  };

  interface HTMLMvsMobMenuElement extends Components.MvsMobMenu, HTMLStencilElement {}
  var HTMLMvsMobMenuElement: {
    prototype: HTMLMvsMobMenuElement;
    new (): HTMLMvsMobMenuElement;
  };

  interface HTMLMvsNavbarElement extends Components.MvsNavbar, HTMLStencilElement {}
  var HTMLMvsNavbarElement: {
    prototype: HTMLMvsNavbarElement;
    new (): HTMLMvsNavbarElement;
  };

  interface HTMLMvsNavbuttonElement extends Components.MvsNavbutton, HTMLStencilElement {}
  var HTMLMvsNavbuttonElement: {
    prototype: HTMLMvsNavbuttonElement;
    new (): HTMLMvsNavbuttonElement;
  };

  interface HTMLMvsOverlineElement extends Components.MvsOverline, HTMLStencilElement {}
  var HTMLMvsOverlineElement: {
    prototype: HTMLMvsOverlineElement;
    new (): HTMLMvsOverlineElement;
  };

  interface HTMLMvsParagraphElement extends Components.MvsParagraph, HTMLStencilElement {}
  var HTMLMvsParagraphElement: {
    prototype: HTMLMvsParagraphElement;
    new (): HTMLMvsParagraphElement;
  };

  interface HTMLMvsPreElement extends Components.MvsPre, HTMLStencilElement {}
  var HTMLMvsPreElement: {
    prototype: HTMLMvsPreElement;
    new (): HTMLMvsPreElement;
  };

  interface HTMLMvsStrongElement extends Components.MvsStrong, HTMLStencilElement {}
  var HTMLMvsStrongElement: {
    prototype: HTMLMvsStrongElement;
    new (): HTMLMvsStrongElement;
  };

  interface HTMLMvsSubtitleElement extends Components.MvsSubtitle, HTMLStencilElement {}
  var HTMLMvsSubtitleElement: {
    prototype: HTMLMvsSubtitleElement;
    new (): HTMLMvsSubtitleElement;
  };

  interface HTMLMvsTitleElement extends Components.MvsTitle, HTMLStencilElement {}
  var HTMLMvsTitleElement: {
    prototype: HTMLMvsTitleElement;
    new (): HTMLMvsTitleElement;
  };

  interface HTMLMvsTooltipElement extends Components.MvsTooltip, HTMLStencilElement {}
  var HTMLMvsTooltipElement: {
    prototype: HTMLMvsTooltipElement;
    new (): HTMLMvsTooltipElement;
  };
  interface HTMLElementTagNameMap {
    'mvs-anchor': HTMLMvsAnchorElement;
    'mvs-app-bar': HTMLMvsAppBarElement;
    'mvs-base': HTMLMvsBaseElement;
    'mvs-bg': HTMLMvsBgElement;
    'mvs-button': HTMLMvsButtonElement;
    'mvs-card': HTMLMvsCardElement;
    'mvs-divider': HTMLMvsDividerElement;
    'mvs-figure': HTMLMvsFigureElement;
    'mvs-figure-caption': HTMLMvsFigureCaptionElement;
    'mvs-flexgrid': HTMLMvsFlexgridElement;
    'mvs-iconbutton': HTMLMvsIconbuttonElement;
    'mvs-mark': HTMLMvsMarkElement;
    'mvs-mob-button': HTMLMvsMobButtonElement;
    'mvs-mob-drawer': HTMLMvsMobDrawerElement;
    'mvs-mob-menu': HTMLMvsMobMenuElement;
    'mvs-navbar': HTMLMvsNavbarElement;
    'mvs-navbutton': HTMLMvsNavbuttonElement;
    'mvs-overline': HTMLMvsOverlineElement;
    'mvs-paragraph': HTMLMvsParagraphElement;
    'mvs-pre': HTMLMvsPreElement;
    'mvs-strong': HTMLMvsStrongElement;
    'mvs-subtitle': HTMLMvsSubtitleElement;
    'mvs-title': HTMLMvsTitleElement;
    'mvs-tooltip': HTMLMvsTooltipElement;
  }
}

declare namespace LocalJSX {
  interface MvsAnchor extends JSXBase.HTMLAttributes<HTMLMvsAnchorElement> {
    'href'?: string;
  }
  interface MvsAppBar extends JSXBase.HTMLAttributes<HTMLMvsAppBarElement> {
    'color'?: 'inherit' | 'primary' | 'secondary' | 'default';
    'position'?: 'fixed' | 'sticky' | 'absolute' | 'static' | 'relative';
  }
  interface MvsBase extends JSXBase.HTMLAttributes<HTMLMvsBaseElement> {}
  interface MvsBg extends JSXBase.HTMLAttributes<HTMLMvsBgElement> {}
  interface MvsButton extends JSXBase.HTMLAttributes<HTMLMvsButtonElement> {
    /**
    * Caso `true`, desabilita o botão.
    */
    'disabled'?: boolean;
    /**
    * Caso `true`, botão terá largura 100%.
    */
    'full'?: boolean;
    /**
    * Caso `true`, botão não terá margens.
    */
    'marginzero'?: boolean;
    /**
    * Define o tipo do botão.
    */
    'type'?: 'button' | 'submit' | 'reset';
    /**
    * Define estilo do botão.
    */
    'variant'?: 'text' | 'outlined' | 'contained';
  }
  interface MvsCard extends JSXBase.HTMLAttributes<HTMLMvsCardElement> {
    'button'?: string;
    'cardtitle'?: any;
    'link'?: string;
    'overline'?: any;
    'subtitle'?: any;
    'width'?: number;
  }
  interface MvsDivider extends JSXBase.HTMLAttributes<HTMLMvsDividerElement> {}
  interface MvsFigure extends JSXBase.HTMLAttributes<HTMLMvsFigureElement> {
    'alt'?: string;
    'src'?: string;
  }
  interface MvsFigureCaption extends JSXBase.HTMLAttributes<HTMLMvsFigureCaptionElement> {
    'alt'?: string;
    'bold'?: boolean;
    'boldspotlight'?: boolean;
    'boldtext'?: boolean;
    'italic'?: boolean;
    'italicspotlight'?: boolean;
    'italictext'?: boolean;
    'src'?: string;
  }
  interface MvsFlexgrid extends JSXBase.HTMLAttributes<HTMLMvsFlexgridElement> {
    /**
    * Altera visualização de flex para block.
    */
    'block'?: boolean;
    /**
    * Caso `true`, o componente se comportará como `container` capaz de receber `items`.
    */
    'container'?: boolean;
    /**
    * Caso `true`, o componente se comportará como `item`, contido em um `container`.
    */
    'item'?: boolean;
    /**
    * Largura do componente no breakpoint Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'lg'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Medium, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'md'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Largura do componente no breakpoint Small, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'sm'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
    /**
    * Define espaçamento entre componentes do tipo `item`. Usando somente em componentes tipo `container`.
    */
    'spacing'?: string;
    /**
    * Largura do componente no breakpoint Extra Large, entre 1 e 12. Quando omitido, ocupa o espaço restante automaticamente.
    */
    'xl'?: true | false | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  }
  interface MvsIconbutton extends JSXBase.HTMLAttributes<HTMLMvsIconbuttonElement> {
    'disabled'?: boolean;
    'type'?: string;
  }
  interface MvsMark extends JSXBase.HTMLAttributes<HTMLMvsMarkElement> {}
  interface MvsMobButton extends JSXBase.HTMLAttributes<HTMLMvsMobButtonElement> {
    'open'?: boolean;
  }
  interface MvsMobDrawer extends JSXBase.HTMLAttributes<HTMLMvsMobDrawerElement> {
    'open'?: boolean;
  }
  interface MvsMobMenu extends JSXBase.HTMLAttributes<HTMLMvsMobMenuElement> {
    'open'?: boolean;
    'setClass'?: string;
  }
  interface MvsNavbar extends JSXBase.HTMLAttributes<HTMLMvsNavbarElement> {
    'setClass'?: string;
  }
  interface MvsNavbutton extends JSXBase.HTMLAttributes<HTMLMvsNavbuttonElement> {
    'contained'?: boolean;
    'disabled'?: boolean;
    'marginzero'?: boolean;
    'outlined'?: boolean;
    'type'?: string;
  }
  interface MvsOverline extends JSXBase.HTMLAttributes<HTMLMvsOverlineElement> {}
  interface MvsParagraph extends JSXBase.HTMLAttributes<HTMLMvsParagraphElement> {
    /**
    * Altera o parágrafo para tamanho reduzido (body 2).
    */
    'bodytwo'?: boolean;
    /**
    * Ativa ou desativa estilização de capitular.
    */
    'capitular'?: boolean;
  }
  interface MvsPre extends JSXBase.HTMLAttributes<HTMLMvsPreElement> {}
  interface MvsStrong extends JSXBase.HTMLAttributes<HTMLMvsStrongElement> {}
  interface MvsSubtitle extends JSXBase.HTMLAttributes<HTMLMvsSubtitleElement> {
    'type'?: string;
  }
  interface MvsTitle extends JSXBase.HTMLAttributes<HTMLMvsTitleElement> {
    /**
    * Define estilo de título a ser usado pelo componente.
    */
    'level'?: true | false | 't1' | 't2' | 't3' | 't4' | 't5' | 't6';
    /**
    * Sobreescreve o tag html definido automaticamente.
    */
    'override'?: true | false | 1 | 2 | 3 | 4 | 5 | 6;
    /**
    * Propriedade interna que define automaticamente a tag H a ser usada.
    */
    'rank'?: number;
    /**
    * Define texto de cor branca, para fundos escuros.
    */
    'white'?: boolean;
  }
  interface MvsTooltip extends JSXBase.HTMLAttributes<HTMLMvsTooltipElement> {
    /**
    * Define conteúdo do tooltip.
    */
    'label'?: string;
    /**
    * Define largura do tooltip.
    */
    'length'?: string;
  }

  interface IntrinsicElements {
    'mvs-anchor': MvsAnchor;
    'mvs-app-bar': MvsAppBar;
    'mvs-base': MvsBase;
    'mvs-bg': MvsBg;
    'mvs-button': MvsButton;
    'mvs-card': MvsCard;
    'mvs-divider': MvsDivider;
    'mvs-figure': MvsFigure;
    'mvs-figure-caption': MvsFigureCaption;
    'mvs-flexgrid': MvsFlexgrid;
    'mvs-iconbutton': MvsIconbutton;
    'mvs-mark': MvsMark;
    'mvs-mob-button': MvsMobButton;
    'mvs-mob-drawer': MvsMobDrawer;
    'mvs-mob-menu': MvsMobMenu;
    'mvs-navbar': MvsNavbar;
    'mvs-navbutton': MvsNavbutton;
    'mvs-overline': MvsOverline;
    'mvs-paragraph': MvsParagraph;
    'mvs-pre': MvsPre;
    'mvs-strong': MvsStrong;
    'mvs-subtitle': MvsSubtitle;
    'mvs-title': MvsTitle;
    'mvs-tooltip': MvsTooltip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


